# Generated by Django 2.1.3 on 2019-01-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20190121_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='linkedin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='linkedin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.Linkedin'),
        ),
    ]
