# Generated by Django 2.1.3 on 2019-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_auto_20190121_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='linkedin',
            field=models.CharField(max_length=200),
        ),
    ]
