# Generated by Django 2.1.3 on 2019-01-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_auto_20190121_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='linkedin',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.Linkedin'),
        ),
    ]
