# Generated by Django 2.1.3 on 2019-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_auto_20190121_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='imagem_usuario',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='linkedin',
            name='imagem_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_usuario/'),
        ),
        migrations.AlterField(
            model_name='linkedin',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
    ]
