# Generated by Django 2.1.7 on 2019-02-23 18:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_auto_20190121_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='texto2',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
    ]
