# Generated by Django 2.1.7 on 2019-02-23 18:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_postagem_texto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='texto2',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
